// RobotBuilder Version: 1.5BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands.autocommands;
import org.usfirst.frc330.commands.*;
import org.usfirst.frc330.constants.LiftPos;
import org.usfirst.frc330.constants.MastPos;

import edu.wpi.first.wpilibj.command.BBCommand;
import edu.wpi.first.wpilibj.command.BBCommandGroup;

/**
 *
 */
public class KitchenSinkConQueso extends BBCommandGroup {
    
    public  KitchenSinkConQueso() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    	
    	//Hold joint angles, open grabbers, close center grabber
    	addParallel(new ArmPID_on());
    	addParallel(new WristPID_on());
    	//addParallel(new LiftPID_on());
    	addSequential(new ShiftLow());
    	addSequential(new OpenAllGrabbers());
    	//addParallel(new MastPID_on());
    	addSequential(new SetMastPosition(120.0, 1.0, 0.3));
    	//addSequential(new DriveDistance(2,0.5,0.5, true));
    	addParallel(new CenterGrabberClose());
    	addSequential(new Wait(0.1));
    	
    	//Adjust the mast to vertical and start raising the arm
    	addParallel(new SetWristAngle(5.0));
    	addSequential(new SetArmPosition(-12.9, 1.0, 0.1));  //Plan on it timing out, and the feedforward finishing this
    	addParallel(new SetMastPosition(MastPos.vertical, 3.0));
    	addSequential(new Wait(0.4));
    	addParallel(new SetArmPosition(33.0, 2.0));
    	addSequential(new Wait(0.1));
    	//addParallel(new SetWristAngle(5.0));
    	
    	//Drive to second station while loading first tote
    	BBCommand driveCommand = new DriveDistanceAtAbsAngle_NoTurn(80.0 , 0.0, 2.0);  //Dist Angl Tol
    	addParallel(driveCommand);
    	addSequential(new SetLiftPosition(LiftPos.dropOff));
    	addSequential(new SetLiftPosition(LiftPos.justOverOneTote));
    	addSequential(new CheckDone(driveCommand));
    	
    	//Pickup second tote
    	addSequential(new SetLiftPosition(LiftPos.dropOff));
    	addParallel(new DriveDistanceAtRelAngle_NoTurn(3.5, 0.0, 0.5));  //Dist Angle Tol
    	addSequential(new Wait(0.7));
    	addParallel(new SetLiftPosition(17.3));
    	addSequential(new Wait(0.3));  //could possibly reduce one tenth
    
    	//Drive back and turn
    	addSequential(new DriveDistanceAtRelAngle_NoTurn(-42 , 0.0, 2.0));  //Dist Angl Tol
    	addSequential(new TurnGyroAbs(14.0, 0.5));  //Angle Tol
    	addSequential(new Wait(0.3));
    	
    	//Drive Forward and Swap Cans
    	addSequential(new SetArmPosition(-17, 4.0));
    	addParallel(new CenterGrabberOpen());
    	addParallel(new SetWristAngle(0));
    	addSequential(new SetArmPosition(-35, 1.0));
    	addSequential(new DriveDistanceAtAbsAngle_NoTurn(32.0 , 14.0, 1.5));  //Dist Angl Tol
    	addSequential(new LeftGrabberClose());
    	addSequential(new CenterGrabberClose());
    	addSequential(new Wait(0.2));
    	
    	//Raise arm and drive back
    	//addSequential(new SetArmPosition(-25, 5.0));
    	//TODO: Consider adding a wrist command here
    	//addSequential(new Wait(2.0));
    	
    	//addSequential(new SetArmPosition(-20, 5.0));
    	//addSequential(new Wait(2.0));
    	addSequential(new DriveDistanceAtRelAngle_NoTurn(-6.0 , 0.0, 2.0));
    	addParallel(new CenterGrabberOpen());
    	addSequential(new DriveDistanceAtRelAngle_NoTurn(-26.0 , 0.0, 2.0));  //Dist Angl Tol
    	//addParallel(new SetArmPosition(-30, 5.0));
    	
    	//Straighten Out and drive to left behind can
    	addSequential(new TurnGyroAbs(0.0, 0.5));  //Angle Tol
    	addSequential(new Wait(0.3));
    	driveCommand = new DriveDistanceAtAbsAngle_NoTurn(32.0 , 0.0, 2.0);
    	addParallel(driveCommand);  //Dist Angl Tol
    	
    	//Raise the tote stacker so I can put the arm extra low
    	//addSequential(new SetArmPosition(-22, 5.0));
    	//addSequential(new SetLiftPosition(LiftPos.stack3, 3.0));
    	addSequential(new CheckDone(driveCommand));
    	
    	//Move arm to setdown totes position
    	//addSequential(new SetArmPosition(-22, 5.0)); // TODO: Adjust this position
    	//addSequential(new Wait(3.0));
    	//addParallel(new LeftGrabberOpen());
    	//addSequential(new Wait(0.1));
    	//addSequential(new SetArmPosition(-30, 5.0));
    	//addSequential(new Wait(0.3));
    	//addSequential(new SetWristAngle(-5.0));
    	addSequential(new RightGrabberClose());
    	//addSequential(new LeftGrabberClose());
    	addSequential(new Wait(0.3));
    	//addParallel(new SetWristAngle(5.0));
    	addParallel(new SetArmPosition(-10, 5.0));
    	
    	//Lift cans
    	//addParallel(new SetArmPosition(-5.0, 2.0));
    	
    	//Time to clear the field (REMOVE)
    	addSequential(new Wait(1.0));
    	
    	//Drive to last location
    	driveCommand = new DriveDistanceAtAbsAngle_NoTurn(85.0 , 0.0, 2.0);  //Dist Angl Tol
    	addParallel(driveCommand);
    	addParallel(new SetLiftPosition(LiftPos.justOverOneTote));
    	addSequential(new Wait(0.6));
    	addParallel(new SetArmPosition(-8.0, 1.0));
    	addSequential(new CheckDone(driveCommand));
    	
    	//Grab last can
    	addParallel(new CenterGrabberClose());
    	addSequential(new Wait(0.2));
    	addParallel(new SetArmPosition(90.0, 1.0));
    	
    	//Drive to last tote
    	addSequential(new DriveDistanceAtAbsAngle_NoTurn(13.0 , 0.0, 2.0));
    	
    	//Load third tote
    	addSequential(new SetLiftPosition(LiftPos.dropOff));
    	addParallel(new DriveDistanceAtRelAngle_NoTurn(6.0, 0.0, 1.5));  //Dist Angle Tol
    	addSequential(new Wait(0.7));
    	addParallel(new SetLiftPosition(LiftPos.carry));
    	addSequential(new Wait(0.3));  //could possibly reduce one tenth
    	
    	//Grab third Can
    	addParallel(new CenterGrabberClose());
    	addSequential(new Wait(0.1));
    	
    	
    	//Turn 90
    	addSequential(new TurnGyroAbs(90.0, 5.0));  //Angle Tol
    	addSequential(new DriveDistanceAtAbsAngle_NoTurn(120.0, 90.0, 4.0));  //Dist Angl Tol
    	addSequential(new SetLiftPosition(LiftPos.dropOff));
    	addSequential(new DriveDistanceAtAbsAngle_NoTurn(-10.0, 90.0, 4.0));  //Dist Angl Tol
    	addSequential(new BuzzerBeepTimed());
    	addSequential(new BuzzerBeepTimed());
    	addSequential(new BuzzerBeepTimed());
    	
    }
}
