// RobotBuilder Version: 1.5BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands.autocommands;
import org.usfirst.frc330.commands.DriveDistance;
import org.usfirst.frc330.commands.DriveDistanceAtAbsAngle;
import org.usfirst.frc330.commands.DriveDistanceAtAbsAngle_NoTurn;
import org.usfirst.frc330.commands.ExtendCanBurglar;
import org.usfirst.frc330.commands.LeftGrabberClose;
import org.usfirst.frc330.commands.OpenAllGrabbers;
import org.usfirst.frc330.commands.RightGrabberClose;
import org.usfirst.frc330.commands.ShiftLow;
import org.usfirst.frc330.commands.Wait;
import org.usfirst.frc330.constants.ChassisConst;
import org.usfirst.frc330.wpilibj.PIDGains;

import edu.wpi.first.wpilibj.command.BBCommandGroup;

/**
 *
 */
public class LadronRapido extends BBCommandGroup {
    
    public  LadronRapido() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    	
    	//double p, double i, double d, double f, double maxOutput, double maxOutputStep, String name
    	PIDGains driveLow = new PIDGains(0.1,0,0,0,1,1, "DriveLowAggressive");
    	addSequential(new ExtendCanBurglar());
    	addSequential(new ShiftLow());
    	addSequential(new Wait(0.25));
    	addSequential(new DriveDistance(77, 2, 10, false, driveLow, ChassisConst.DriveHigh)); //distance, distanceTolerance, timeout, stopAtEnd, PIDlow, PIDhigh
    }
}
