// RobotBuilder Version: 1.5BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands;	


import edu.wpi.first.wpilibj.command.BBCommand;
import edu.wpi.first.wpilibj.command.Scheduler;

import org.usfirst.frc330.Robot;

/**
 *
 */
public class  KillAll extends BBCommand {

    public KillAll() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    	requires(Robot.chassis);
    	requires(Robot.arm);
    	requires(Robot.mast);
    	requires(Robot.hand);
    	requires(Robot.frills);
    	requires(Robot.powerDP);
    	requires(Robot.lift);
    	
    	this.setRunWhenDisabled(true);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.hand.setHandLevelActivated(false);
    	Scheduler.getInstance().removeAll();
    	Robot.chassis.stopDrive();
    	Robot.arm.stopArm();
    	Robot.lift.stopLift();
    	Robot.hand.stopHand();
    	Robot.mast.stopMast();
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return true;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
