// RobotBuilder Version: 1.5BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands.commandgroups;
import org.usfirst.frc330.commands.CenterGrabberOpen;
import org.usfirst.frc330.commands.SetArmPosition;
import org.usfirst.frc330.commands.SetMastPosition;
import org.usfirst.frc330.commands.SetWristAngle;
import org.usfirst.frc330.conditionalWrappers.MoveArmToRear;

import edu.wpi.first.wpilibj.command.BBCommandGroup;

/**
 *
 */
public class CanSnatchStart extends BBCommandGroup {
    
    public  CanSnatchStart() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    	
    	addSequential(new MoveArmToRear());
    	addParallel(new SetArmPosition(90.0, 1.0, 1.5));
//    	addSequential(new Wait(0.5));
    	
    	//Open Center Grabber
    	addSequential(new CenterGrabberOpen());
    	
    	//Lower mast
    	//addSequential(new SetMastPosition(MastPos.rearLimitAngle, 1.0, 1.0)); //angle tol timeout
    	addSequential(new SetMastPosition(145.0, 1.0, 1.0)); //angle tol timeout
    	
    	//Aim hand, lower arm
    	addParallel(new SetWristAngle(190.0,1.0,1.5));
    	addSequential(new SetArmPosition(175.0, 1.5, 1.5)); //angle tolerance timeout
    	// was 170
//    	addSequential(new Wait(0.5));
    	addParallel(new SetWristAngle(180.0,1.0,1.5));
    	addSequential(new SetArmPosition(175.0, 1.5, 1.5));
    }
}
