// RobotBuilder Version: 1.5BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.commands.commandgroups;
import org.usfirst.frc330.commands.*;
import org.usfirst.frc330.conditionalWrappers.*;
import org.usfirst.frc330.constants.MastPos;

import edu.wpi.first.wpilibj.command.BBCommand;
import edu.wpi.first.wpilibj.command.BBCommandGroup;

/**
 *
 */
public class CanSnatch extends BBCommandGroup {
    
    public  CanSnatch() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    	
    	
    	//Make Sure the Arm is in Back
    	addSequential(new MoveArmToRear());
    	addParallel(new SetArmPosition(90.0, 1.0, 1.5));
    	addSequential(new Wait(0.5));
    	addSequential(new Wait(3.30));
    	
    	//Open Center Grabber
    	addSequential(new CenterGrabberOpen());
    	
    	//Lower mast
    	addSequential(new SetMastPosition(123.0, 1.0, 1.0)); //angle tol timeout
    	addSequential(new Wait(3.30));
    	
    	//Aim hand, lower arm
    	addParallel(new SetWristAngle(180.0));
    	addSequential(new SetArmPosition(184.0, 1.0, 1.5)); //angle tolerance timeout
    	addSequential(new Wait(0.4));
    	addSequential(new Wait(3.30));
    	
    	//Fine tune position
    	
    	//Grab Cans
    	addSequential(new CenterGrabberClose());
    	addSequential(new Wait(0.1));
    	
    	//Pickup the can
    	addSequential(new SetArmPosition(90.0, 1.0, 1.5));
    	addSequential(new Wait(3.30));
    	
    	//Raise the mast
    	addSequential(new SetMastPosition(123.0, 1.0, 1.0)); //angle tol timeout
    	addSequential(new Wait(3.30));
    	
    	//    	addSequential(new SetArmPosition(116.0, 5.0, 1.0));
//    	addSequential(new Wait(0.2));
//    	
//    	//Move back and drop cans
//    	addSequential(new DriveDistanceAtAbsAngle_NoTurn(14.0 , 0.0, 1.0));
//    	addSequential(new Wait(0.3));
//    	addSequential(new OpenAllGrabbers());
//    	addSequential(new Wait(0.1));
//    	addParallel(new SetWristAngle(245.0));
//    	addSequential(new SetArmPosition(105.0, 1.0, 1.5));
//    	addSequential(new Wait(0.1));
//    	
//    	//Drive Out
//    	//addSequential(new ShiftHigh());
//    	addParallel(new SetWristAngle(180.0));
//    	addSequential(new SetMastPosition(MastPos.vertical, 5.0, 0.8));  //Angle Tolerance Timeout
//    	addParallel(new DriveDistanceAtAbsAngle_NoTurn(72.0 , 0.0, 6.0)); //Dist Angl Tol
//    	addSequential(new Wait (0.3));
//    	addParallel(new SetArmPosition(90.0, 1.0, 1.5));
    }
}
