// RobotBuilder Version: 1.5BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.subsystems;

import org.usfirst.frc330.RobotMap;
import org.usfirst.frc330.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Chassis extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Solenoid shift = RobotMap.chassisshift;
    DoubleSolenoid mast = RobotMap.chassismast;
    Compressor compressor = RobotMap.chassiscompressor;
    AnalogInput pressureSensor = RobotMap.chassispressureSensor;
    Encoder driveTrainEncoderL = RobotMap.chassisdriveTrainEncoderL;
    Encoder driveTrainEncoderR = RobotMap.chassisdriveTrainEncoderR;
    SpeedController chassisLeftDrive1 = RobotMap.chassischassisLeftDrive1;
    SpeedController chassisLeftDrive2 = RobotMap.chassischassisLeftDrive2;
    SpeedController chassisRightDrive1 = RobotMap.chassischassisRightDrive1;
    SpeedController chassisRightDrive2 = RobotMap.chassischassisRightDrive2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

