// RobotBuilder Version: 1.5BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.subsystems;

import org.usfirst.frc330.Robot;
import org.usfirst.frc330.RobotMap;
import org.usfirst.frc330.util.CSVLoggable;
import org.usfirst.frc330.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class PowerDP extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    PowerDistributionPanel pDP = RobotMap.powerDPPDP;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new UpdatePDP());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    double currents[] = new double[16];
    double totalCurrent = 0;
    double totalPower = 0;
    int counter = 0;
    
    public PowerDP() {
    	
    	CSVLoggable temp = new CSVLoggable() {
			public double get() { return getTotalCurrent(); }
    	};
    	Robot.csvLogger.add("PDPTotalCurrent", temp);
    	
    	temp = new CSVLoggable() {
			public double get() { return getTotalPower(); }
    	};
    	Robot.csvLogger.add("PDPTotalPower", temp);
    }

    /////////////////////////////////////////////////////////////
    // SET methods
    /////////////////////////////////////////////////////////////     
    
    /////////////////////////////////////////////////////////////
    // GET methods
    /////////////////////////////////////////////////////////////  

    //TODO renable current and test speed.
    public double getTotalCurrent() {
    	return totalCurrent;
    }
    
    private double getCurrent(int channel) {
    	return pDP.getCurrent(channel);
    }
    
    public double getTotalPower() {
    	return totalPower;
    }
    
    //Get motor current methods
    
    public double getChassisLeftDrive1Current() {
    	return currents[1];
    }
    
    public double getChassisLeftDrive2Current() {
    	return currents[2];
    }
    
    public double getChassisRightDrive1Current() {
    	return currents[13];
    }
    
    public double getChassisRightDrive2Current() {
    	return currents[14];
    }
    
    public double getLiftLeftCurrent() {
    	return currents[6];
    }
    
    public double getLiftRightCurrent() {
    	return currents[9];
    }
    
    public double getArmLeftCurrent() {
    	return currents[5];
    }
    
    public double getArmRightCurrent() {
    	return currents[10];
    }
    
    public double getWristLeftCurrent() {
    	return currents[4];
    }
    
    public double getWristRightCurrent() {
    	return currents[11];
    }
    
    public double getMastLeftCurrent() {
    	return currents[0];
    }
    
    public double getMastRightCurrent() {
    	return currents[5];
    }
    
    public void updatePDP() {
    	if (counter <16) {
    		currents[counter] = pDP.getCurrent(counter); 
    		counter++;
    	}
    	else if (counter == 16) {
    		totalCurrent = pDP.getTotalCurrent(); 
    		counter++;
    	}
    	else if (counter == 17) {
    		totalPower = pDP.getTotalPower();
    		counter =0;
    	}
    }
    
}

