// RobotBuilder Version: 1.5BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.subsystems;

import org.usfirst.frc330.Robot;
import org.usfirst.frc330.RobotMap;
import org.usfirst.frc330.util.CSVLoggable;
import org.usfirst.frc330.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class PowerDP extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    PowerDistributionPanel pDP = RobotMap.powerDPPDP;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public PowerDP() {
    	CSVLoggable temp = new CSVLoggable() {
			public double get() { return getTemperature(); }
    	};
    	Robot.csvLogger.add("PDPTemperature", temp);
    	
    	temp = new CSVLoggable() {
			public double get() { return getTotalCurrent(); }
    	};
    	Robot.csvLogger.add("PDPTotalCurrent", temp);
    	
    	temp = new CSVLoggable() {
			public double get() { return getTotalPower(); }
    	};
    	Robot.csvLogger.add("PDPTotalPower", temp);
    }

    /////////////////////////////////////////////////////////////
    // SET methods
    /////////////////////////////////////////////////////////////     
    
    /////////////////////////////////////////////////////////////
    // GET methods
    /////////////////////////////////////////////////////////////  
    public double getTemperature(){ 
    	return pDP.getTemperature();
    }
    
    public double getTotalCurrent() {
    	return pDP.getTotalCurrent();
    }
    
    public double getCurrent(int channel) {
    	return pDP.getCurrent(channel);
    }
    
    public double getTotalPower() {
    	return pDP.getTotalPower();
    }
    
    //Get motor current methods
    
    public double getChassisLeftDrive1Current() {
    	return pDP.getCurrent(0);
    }
    
    public double getChassisLeftDrive2Current() {
    	return pDP.getCurrent(1);
    }
    
    public double getChassisRightDrive1Current() {
    	return pDP.getCurrent(2);
    }
    
    public double getChassisRightDrive2Current() {
    	return pDP.getCurrent(3);
    }
    
    public double getLiftLeftCurrent() {
    	return pDP.getCurrent(4);
    }
    
    public double getLiftRightCurrent() {
    	return pDP.getCurrent(5);
    }
    
    public double getArmLeftCurrent() {
    	return pDP.getCurrent(6);
    }
    
    public double getArmRightCurrent() {
    	return pDP.getCurrent(7);
    }
    
    public double getWristLeftCurrent() {
    	return pDP.getCurrent(8);
    }
    
    public double getWristRightCurrent() {
    	return pDP.getCurrent(9);
    }
    
    public double getMastLeftCurrent() {
    	return pDP.getCurrent(10);
    }
    
    public double getMastRightCurrent() {
    	return pDP.getCurrent(11);
    }
    
}

