// RobotBuilder Version: 1.5BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

import java.util.Vector;

import org.usfirst.frc330.wpilibj.BBDoubleSolenoid;
import org.usfirst.frc330.wpilibj.DualSpeedController;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DigitalOutput frillslights;
    public static DigitalInput frillspracticeRobot;
    public static DigitalOutput frillsbuzzer;
    public static Compressor chassiscompressor;
    public static AnalogInput chassispressureSensor;
    public static Encoder chassisdriveTrainEncoderL;
    public static Encoder chassisdriveTrainEncoderR;
    public static SpeedController chassischassisLeftDrive1;
    public static SpeedController chassischassisLeftDrive2;
    public static DualSpeedController chassischassisLeftDrive;
    public static SpeedController chassischassisRightDrive1;
    public static SpeedController chassischassisRightDrive2;
    public static DualSpeedController chassischassisRightDrive;
    public static BBDoubleSolenoid chassisshift;
    public static BBDoubleSolenoid lifttotePincher;
    public static SpeedController liftliftLeft;
    public static SpeedController liftliftRight;
    public static DualSpeedController liftLift;
    public static AnalogInput liftliftPot;
    public static AnalogInput armarmPot;
    public static SpeedController armarmLeft;
    public static SpeedController armarmRight;
    public static DualSpeedController armarm;
    public static BBDoubleSolenoid handhandLeft;
    public static BBDoubleSolenoid handhandCenter;
    public static BBDoubleSolenoid handhandRight;
    public static SpeedController handwristLeft;
    public static SpeedController handwristRight;
    public static DualSpeedController handwrist;
    public static AnalogInput handwristPot;
    public static PowerDistributionPanel powerDPPDP;
    public static SpeedController mastmastRight;
    public static SpeedController mastmastLeft;
    public static DualSpeedController mastmast;
    public static AnalogInput mastmastPot;
    public static BBDoubleSolenoid mastmastLock;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        frillslights = new DigitalOutput(8);
        LiveWindow.addActuator("Frills", "lights", frillslights);
        
        frillspracticeRobot = new DigitalInput(9);
        LiveWindow.addSensor("Frills", "practiceRobot", frillspracticeRobot);
        
        frillsbuzzer = new DigitalOutput(2);
        LiveWindow.addActuator("Frills", "buzzer", frillsbuzzer);
        
        chassiscompressor = new Compressor(0);
        
        
        chassispressureSensor = new AnalogInput(3);
        LiveWindow.addSensor("Chassis", "pressureSensor", chassispressureSensor);
        
        chassisdriveTrainEncoderL = new Encoder(4, 5, false, EncodingType.k4X);
        LiveWindow.addSensor("Chassis", "driveTrainEncoderL", chassisdriveTrainEncoderL);
        chassisdriveTrainEncoderL.setDistancePerPulse(1.0);
        chassisdriveTrainEncoderL.setPIDSourceParameter(PIDSourceParameter.kDistance);
        chassisdriveTrainEncoderR = new Encoder(6, 7, true, EncodingType.k4X);
        LiveWindow.addSensor("Chassis", "driveTrainEncoderR", chassisdriveTrainEncoderR);
        chassisdriveTrainEncoderR.setDistancePerPulse(1.0);
        chassisdriveTrainEncoderR.setPIDSourceParameter(PIDSourceParameter.kDistance);
        chassischassisLeftDrive1 = new VictorSP(0);
        LiveWindow.addActuator("Chassis", "chassisLeftDrive1", (VictorSP) chassischassisLeftDrive1);
        
        chassischassisLeftDrive2 = new VictorSP(1);
        LiveWindow.addActuator("Chassis", "chassisLeftDrive2", (VictorSP) chassischassisLeftDrive2);
        
        chassischassisLeftDrive = new DualSpeedController(chassischassisLeftDrive1, chassischassisLeftDrive2, true, true);
        LiveWindow.addActuator("Chassis", "chassisLeftDrive", chassischassisLeftDrive);
        
        chassischassisRightDrive1 = new VictorSP(2);
        LiveWindow.addActuator("Chassis", "chassisRightDrive1", (VictorSP) chassischassisRightDrive1);
        
        chassischassisRightDrive2 = new VictorSP(3);
        LiveWindow.addActuator("Chassis", "chassisRightDrive2", (VictorSP) chassischassisRightDrive2);
        
        chassischassisRightDrive = new DualSpeedController(chassischassisRightDrive1, chassischassisRightDrive2, false, false);
        LiveWindow.addActuator("Chassis", "chassisRightDrive", chassischassisRightDrive);
        
        chassisshift = new BBDoubleSolenoid(1, 0, 1);      
        LiveWindow.addActuator("Chassis", "shift", chassisshift);
        
        lifttotePincher = new BBDoubleSolenoid(1, 3, 2);      
        LiveWindow.addActuator("Lift", "totePincher", lifttotePincher);
        
        liftliftLeft = new Victor(4);
        LiveWindow.addActuator("Lift", "liftLeft", (Victor) liftliftLeft);
        
        liftliftRight = new Victor(5);
        LiveWindow.addActuator("Lift", "liftRight", (Victor) liftliftRight);
        
        liftLift = new DualSpeedController(liftliftLeft, liftliftRight, false, true);
        LiveWindow.addActuator("Lift", "Lift", liftLift);
        
        liftliftPot = new AnalogInput(4);
        LiveWindow.addSensor("Lift", "liftPot", liftliftPot);
        
        armarmPot = new AnalogInput(1);
        LiveWindow.addSensor("Arm", "armPot", armarmPot);
        
        armarmLeft = new Talon(6);
        LiveWindow.addActuator("Arm", "armLeft", (Talon) armarmLeft);
        
        armarmRight = new Talon(7);
        LiveWindow.addActuator("Arm", "armRight", (Talon) armarmRight);
        
        armarm = new DualSpeedController(armarmLeft, armarmRight, false, true);
        LiveWindow.addActuator("Arm", "arm", armarm);
        
        handhandLeft = new BBDoubleSolenoid(0, 0, 1);      
        LiveWindow.addActuator("Hand", "handLeft", handhandLeft);
        
        handhandCenter = new BBDoubleSolenoid(0, 2, 3);      
        LiveWindow.addActuator("Hand", "handCenter", handhandCenter);
        
        handhandRight = new BBDoubleSolenoid(0, 4, 5);      
        LiveWindow.addActuator("Hand", "handRight", handhandRight);
        
        handwristLeft = new Jaguar(8);
        LiveWindow.addActuator("Hand", "wristLeft", (Jaguar) handwristLeft);
        
        handwristRight = new Jaguar(9);
        LiveWindow.addActuator("Hand", "wristRight", (Jaguar) handwristRight);
        
        handwrist = new DualSpeedController(handwristLeft, handwristRight, false, true);
        LiveWindow.addActuator("Hand", "wrist", handwrist);
        
        handwristPot = new AnalogInput(0);
        LiveWindow.addSensor("Hand", "wristPot", handwristPot);
        
        powerDPPDP = new PowerDistributionPanel();
        LiveWindow.addActuator("PowerDP", "PDP", powerDPPDP);
        
        mastmastRight = new Talon(11);
        LiveWindow.addActuator("Mast", "mastRight", (Talon) mastmastRight);
        
        mastmastLeft = new Talon(10);
        LiveWindow.addActuator("Mast", "mastLeft", (Talon) mastmastLeft);
        
        mastmast = new DualSpeedController(mastmastLeft, mastmastRight, false, true);
        LiveWindow.addActuator("Mast", "mast", mastmast);
        
        mastmastPot = new AnalogInput(2);
        LiveWindow.addSensor("Mast", "mastPot", mastmastPot);
        
        mastmastLock = new BBDoubleSolenoid(0, 7, 6);      
        LiveWindow.addActuator("Mast", "mastLock", mastmastLock);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
